name: AI Court Cases Tracker

on:
  schedule:
    - cron: '0 14 * * 1'   # Mondays 14:00 UTC
  workflow_dispatch:

permissions:
  contents: write          # allow git push from the workflow

jobs:
  track-cases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # keep GITHUB_TOKEN for push
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run tracker
        run: |
          python case_tracker.py

      - name: Commit & push changes (if any)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/cases.json docs/index.html
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(tracker): refresh cases.json and index.html [skip ci]"
            git push
          fi
