name: track-cases

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (unbuffered)
        run: |
          set -x
          python -u case_tracker.py

      - name: Show docs dir
        run: |
          echo "::group::docs listing"
          ls -lah docs || true
          echo "::endgroup::"
          echo "::group::preview cases.json head"
          head -c 2000 docs/cases.json || true
          echo
          echo "::endgroup::"

      - name: Commit website changes (docs/)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update cases.json and index.html"
            git push
          fi
