name: track-cases

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"  # every 6 hours at :17 past

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (unbuffered)
        run: |
          set -x
          python -u case_tracker.py

      - name: Commit website changes (docs/)
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update cases.json and index.html"
            git push
          fi
